# Generated by Django 2.0.13 on 2022-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beauth',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='consume',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_category', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='drinking',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='eating',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='gift',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='health',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='phonefee',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='save_money',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='taxing',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='traffic',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='utility_bill',
            fields=[
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
