# Generated by Django 2.0.13 on 2022-04-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_category', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
