# Generated by Django 2.0.13 on 2022-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting_backend', '0002_drinking_eating'),
    ]

    operations = [
        migrations.CreateModel(
            name='beauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='phonefee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='save_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='taxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='utility_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_item', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_price', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
